# deploy locally on raspberry pi with single node swarm cluster

version: "3.4"

services:

  postgres:
    image: postgres:13.1
    networks:
      - main
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHORT_SHA}
    networks:
      - main
    command:
      - "gunicorn"
      - "-t"
      - "1000"
      - "-b"
      - "0.0.0.0:8000"
      - "--log-level"
      - "error"
      - "backend.wsgi"
    env_file:
      - .env.prod
    volumes:
      - backendassets:/code/assets
    depends_on:
      - postgres
      - redis

  nuxt:
    image: ${CI_REGISTRY_IMAGE}/nuxt:${CI_COMMIT_SHORT_SHA}
    networks:
      - main

  web:
    image: ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_SHORT_SHA}
    networks:
      - main
    ports:
      - "80:80"
    volumes:
      - backendassets:/usr/src/app/assets


networks:
  main:
    driver: overlay

volumes:
  backendassets:
    name: backendassets
  redisdata:
    name: redisdata
  pgdata:
    name: pgdata
